name: Docker builds dima_api

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push 
        id: docker_build 
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: krstphr/dima_api:latest

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker service update api_services_dima_api \
            --image=docker.io/krstphr/dima_api:latest \
            